server:
  port: 9007
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
app:
  stat-dir: ${STAT_DIR:/tmp/8424227}

smoketest:
  enabled: false


pulsar:
  url: pulsar://localhost:6650
  topic: persistent://public/default/my-new-topic
  subscription: equity-sub
  token: ""        # 有就填，无就留空
  threads: 4       # 消费线程数
  idle-seconds: 60 # 静默多少秒算无新消息
  callback-url: http://82.202.169.44:6000/callback2
  omr-acc: 8424227
  omr-pwd: 762687ok@

mq:
  concurrency: 4        # 消费线程数
  quiet-secs: 30        # 静默多少秒算完成
  callback:
    url: http://82.202.169.44:6000/callback2
    acc: 8424227
    pwd: 762687ok@


#pulsar:
#  service-url: pulsar://tdmq2broker-nm.t.bocsys.cn:6650
#  auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
#  auth-params: eyJrZXIJZC16InB1bHNhci03ajhicjU4YXhIZWUiLCJhbGciOiJIUzI1NiJ9...
#  tenant: pulsar-7j8br58axeee
#  namespace: public_namespace
#  topic: skill_competition
#  subscription-name: ${SUBSCRIPTION_NAME:equity-sub}
#  subscription-type: Shared


#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver   # GaussDB 和 openGauss 用 PG 驱动
#    url: jdbc:postgresql://${gaussdbIpPort}/${gaussdbDatabase}?currentSchema=${gaussdbSchema}
#    username: ${gaussdbUser}
#    password: ${gaussdbPwd}
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 2
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1800000